### ISSUE TITLE
Spotify doesn't launch when the Spotify.pkg recipe is used.

### ISSUE THREAD

**Issue by SeanHansell** [autopkg/homebysix-recipes#104]
Spotify borked the permissions on their .app bundle. The Spotify executable (./Contents/MacOS/Spotify) is chmod 0744. When the app is installed manually by a user, this is not an issue, but the recipe makes the owner root. So when the app is installed, only root can launch the app. Need to fix the app bundle in the pkg recipe.

**Comment by homebysix** [comment]
Hi @SeanHansell — Have you had a chance to test more on the package payload modes?
