### ISSUE TITLE
TableauReader.download.recipe change to .app name 

### ISSUE THREAD

**Issue by multiday** [autopkg/homebysix-recipes#109]
Getting error that Processor: Versioner: Error: File ... /expanded/Tableau Reader.app/Contents/Info.plist does not exist or could not be read.

As Tableau Software has changed the name of the app. 

On line 78
	<string>%RECIPE_CACHE_DIR%/expanded/Tableau Reader.app/Contents/Info.plist</string>

now should be
	<string>%RECIPE_CACHE_DIR%/expanded/Tableau Reader 10.3.app/Contents/Info.plist</string>

or some better more generic solution?

**Comment by homebysix** [comment]
Thanks! Should be fixed by bf33fb1342517035506af45683c21251609d0c51.
