### ISSUE TITLE
ParallelsDesktop.pkg.recipe created .pkg installs, but the App fails to launch

### ISSUE THREAD

**Issue by MLBZ521** [autopkg/homebysix-recipes#120]
The package produced by the recipe [ParallelsDesktop.pkg.recipe](https://github.com/autopkg/homebysix-recipes/blob/master/Parallels/ParallelsDesktop.pkg.recipe) will successfully install, however, the App will fail to launch with an error.  Attempted with Major Versions 12 and 11, same results.

Parallels Desktop Launch Error:
```
Parallels Desktop cannot be started.
Please reinstall Parallels Desktop and try again.
Problem ID:  15431
```

Searching in the MacAdmins #autopkg channel yields others expressing the same results.

I've tried manually following the steps that the recipe takes and end up with failed results as well.  I'll continue working on this next week, but wanted to go ahead and file this issue.

**Comment by homebysix** [comment]
Noted, thank you!

**Comment by MLBZ521** [comment]
As mentioned in Slack earlier and posting here for reference as well.

I found that a straight ‘copy’ (`cp -r`) of the `Parallels Desktop.app` (from inside the .dmg) doesn’t produce a useable file (results in 1.2GB file from a ~500MB file).  But doing `cp -pR` and it works like a charm.

Not having any luck finding a work around at the moment...outside of wrapping the .dmg into a .pkg with a postinstall script with the logic to perform the install.

If you have any suggestions, feel free to let me know.

**Comment by MLBZ521** [comment]
Well, I held this workaround in by back pocket in case I couldn't do it another way.  If you'd like to use it, it'll 'work' for now.  And it'll continue to support each major version currently listed to be supported by the recipe.  See  #121
