### ISSUE TITLE
Flinto recipe needs DOWNLOAD_URL updated

### ISSUE THREAD

**Issue by blackthroat** [autopkg/homebysix-recipes#124]
`DOWNLOAD_URL` points to `https://www.flinto.com/assets/Flinto.app.zip` which downloads version 1.0.7

Current version is 23.3, which can be downloaded as a .dmg from https://www.flinto.com/mac/download_latest

Recipe Robot didn't seem to have any issues creating it other than the expected:
`[ERROR] Sorry, AutoPkg recipes already exist for this app, and I can't blend new recipes with existing recipes.`

**Comment by homebysix** [comment]
Thanks! If you wouldn't mind submitting a PR, that might get it fixed faster.

**Comment by homebysix** [comment]
Fixed!

**Comment by blackthroat** [comment]
Thank you!
