### ISSUE TITLE
Bartender version has been updated

### ISSUE THREAD

**Issue by krispayne** [autopkg/homebysix-recipes#126]
Bartender updated to version 3, and their URL for download of version 2 is 404'ing:

```
autopkg run -v Bartender.jss
Processing Bartender.jss...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 308
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 3.0.8
SparkleUpdateInfoProvider: Found URL https://macbartender.com/B2/updates/3-0-8/Bartender%25203.zip
URLDownloader
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.
Receipt written to /Users/autopkg/Library/AutoPkg/Cache/local.jss.Bartender/receipts/Bartender-receipt-20171002-090030.plist

The following recipes failed:
Bartender.jss
Error in local.jss.Bartender: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)

Nothing downloaded, packaged or imported.
```

Looks like this is the URL for version3 (from Info.plist):

    <key>SUFeedURL</key>
    <string>https://www.macbartender.com/B2/updates/updatesB3.php</string>
    <key>SUOriginalFeedURL</key>
    <string>https://www.macbartender.com/B2/updates/updatesB3.php</string>

**Comment by homebysix** [comment]
That's an interesting feed URL...

**Comment by krispayne** [comment]
yeah, seems as if it's going through version 2 then 3.

further, that URL gets hit with the SSLv3 bug in recipe robot

**Comment by homebysix** [comment]
@krispayne — Give it a try now, and see whether that works.

**Comment by krispayne** [comment]
👍
