### ISSUE TITLE
GitHub Desktop new version download link

### ISSUE THREAD

**Issue by smashism** [autopkg/homebysix-recipes#127]
I saw the note on the other issue about the differences between versions, but thought I'd still raise an issue none-the-less RE the updated download link for the new version:
https://central.github.com/deployments/desktop/desktop/latest/darwin

🎩

**Comment by homebysix** [comment]
Thanks! You can use the GitHubDesktopBeta.download recipe to grab that version, if needed. I'll wait to update the non-beta GitHubDesktop.download recipe when the old download link no longer works.
