### ISSUE TITLE
GitHubDesktop.munki unattended_install==true should also have blocking_apps check

### ISSUE THREAD

**Issue by jps3** [autopkg/homebysix-recipes#14]
It would be a Good Idea™ to always have a `blocking_apps` ([explanation](https://github.com/munki/munki/wiki/Blocking-Applications)) check if you are going to also set `unattended_install` to `<true/>`. This way you can prevent the app swapping out on a user while they may be in the middle of some work. (Like, say, in the middle of entering a long-ish annotation to a commit.) :-)

**Comment by timsutton** [comment]
See the second item from the explanation link (in [details](https://github.com/munki/munki/wiki/Blocking-Applications#details)).

If a Munki pkginfo contains only copy_from_dmg and applications installs items, `blocking_applications` is not necessary. It _is_ a good idea to use `blocking_applications` when the application is delivered via a pkg, such as Adobe Reader. But the many drag-n-drop apps which Munki installs by copying them from the dmg don't need `blocking_applications` - Munki will do the right thing automatically.

**Comment by homebysix** [comment]
And that's why I love Munki!

But you remind me that my DockerToolbox recipes do need `blocking_applications`, thank you.

**Comment by jps3** [comment]
Tim: I had completely missed that. Or, more likely, that was fixed since I had originally stung myself badly several times when first learning and deploying Munki. :-)  Thank you for the clarification.
