### ISSUE TITLE
AirDroid.download.recipe Failing Code Signature 

### ISSUE THREAD

**Issue by apizz** [autopkg/homebysix-recipes#148]
The AirDroid.download.recipe throws an error when running CodeSignatureVerify on the application.

![screen shot 2018-02-21 at 3 53 06 pm](https://user-images.githubusercontent.com/11789931/36504713-745528a2-171f-11e8-9982-1db27acef93e.png)

**Comment by homebysix** [comment]
Hi @apizz - Please give it another try now. I've updated the code signature requirements. Thank you!
