### ISSUE TITLE
Could not find parent recipe for com.github.homebysix.pkg.Zoom

### ISSUE THREAD

**Issue by haircut** [autopkg/homebysix-recipes#153]
@homebysix It looks like the name of the parent recipe `com.github.hansen-m.download.zoom` has been changed to `com.github.hansen-m.download.zoomus`.

**Comment by homebysix** [comment]
Hi @haircut - This may have been fixed by #151. Try again now?

**Comment by mikecalbreeeezy** [comment]
Hello, I am getting the error message: could not find parent recipe for com.github.homebysix.pkg.Zoom. Is there a fix?

**Comment by homebysix** [comment]
@mikecalbreeeezy The parent recipe for that is `com.github.hansen-m.download.zoomus`. Do you have the hansen-m-recipes repo added?

**Comment by mikecalbreeeezy** [comment]
Hey Elliot,

Thanks for getting back to me. I found the parent recipe and have
successfully deployed the app. Thanks again!
