### ISSUE TITLE
EgnyteDesktopSync failure

### ISSUE THREAD

**Issue by cstout1** [autopkg/homebysix-recipes#156]
RECIPE
local.pkg.EgnyteDesktopSync

MESSAGE
Error in local.pkg.EgnyteDesktopSync: Processor: URLTextSearcher: Error: No match found on URL: https://helpdesk.egnyte.com/hc/en-us/articles/201636844

This recipe has been working fine up until the latest release (9.2.2) from Egnyte.

Current pkg link is: http://egnyte-cdn.egnyte.com/desktopsync/mac/en-us/9.2.2/EgnyteDesktopSync_9.2.2_gd05dbbcc.pkg

**Comment by homebysix** [comment]
Should be fixed by #155.
