### ISSUE TITLE
CocoaPods: fails to run

### ISSUE THREAD

**Issue by franton** [autopkg/homebysix-recipes#159]
Hi,

As discussed on MacAdmin Slack:

I'm running the CocoaPods pkg recipe. It produces a pkg that installs a client that crashes on run. The error logs show that there's a failure in the Sparkle framework inside the .app bundle.

Further investigation shows that your recipe is setting the .app bundle ownership to root:admin but for some reason the sparkle binary inside has 700 permissions.

`drwxr-xr-x@  5 root  admin     160 22 Jan 23:26 .
drwxr-xr-x@  4 root  admin     128 30 Mar 17:39 ..
drwxr-xr-x@ 38 root  admin    1216 30 Mar 17:39 Resources
-rwx------@  1 root  admin  487872 22 Jan 23:26 Sparkle
drwxr-xr-x@  3 root  admin      96 22 Jan 23:26 _CodeSignature`

I've found that the following command will allow the app to run again:

`chmod +rx /Applications/CocoaPods.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle`

**Comment by franton** [comment]
This seems to be a Sparkle issue. The CocoaPods developers have been notified here: [https://github.com/CocoaPods/CocoaPods-app/issues/394](url)

**Comment by homebysix** [comment]
Is this issue still ongoing? I see https://github.com/CocoaPods/CocoaPods-app/issues/394 is still open.

**Comment by franton** [comment]
I just downloaded the latest release. Seems ok now, they just haven’t closed the issue.
