### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by ygini** [autopkg/homebysix-recipes#173]
The Zoom package has an issue, we updated the download script to rely on the enterprise deployment package instead of the end user

Now the pkg one need to be updated too

I've started to work on it https://github.com/ygini/homebysix-recipes/commit/4c10b2882c23b34ae9bb9313f0b47f93adf998d7 but there is still work to do. I'm not sure to have the time this weekend and it's already the end of the day in France.

If someone has the time to continue the work to convert their enterprise deployment package to a proper one, do it. Otherwise I will try to do it ASAP.

**Comment by cwhits** [comment]
@ygini Did you make any more progress on this?

**Comment by ygini** [comment]
Yep

Look on my fork, you will find an updated PKG with dirty hack to fix Zoom package.

I need inputs on this one to eventually find a better way. I didn’t sent a PR yet due to the ugliness of the recipe right now.

**Comment by mpanighetti** [comment]
Seeing an error message when trying to run this recipe, sounds related to the above regarding new installer package structure:

> Error in com.github.homebysix.pkg.Zoom: Processor: Unarchiver: Error: Unarchiving $CACHE_DIR/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip with ditto failed: ditto: $CACHE_DIR/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip: No such file or directory

Looking at [the vendor package that gets downloaded](https://zoom.us/client/latest/ZoomInstallerIT.pkg), it appears that it no longer has a Scripts directory at the expected file path. I don't have access to an older installer so I can't tell if that file has been moved or if the recipe simply doesn't need to perform the associated action anymore.

I'm guessing #177 will address this issue once it's reviewed and merged.

**Comment by krispayne** [comment]
This is still occurring.

Does #177 fix? Are there any other items in the way of the PR?

**Comment by homebysix** [comment]
The only item in the way of merging is me. ;-) I hope to have a chance to test the change soon.

**Comment by krispayne** [comment]
Thanks Elliot!

**Comment by ygini** [comment]
@homebysix there package is a mess, even the "distribution" one…

I've started something here https://github.com/ygini/homebysix-recipes/tree/master/Zoom

But didn't had the time to finish. And clearly, it's dirty.

**Comment by FriedCircuits** [comment]
Is there any word on this working? We just purchased Zoom and I would like to roll it out via Munki.

Thanks!

**Comment by homebysix** [comment]
I've merged #177, and it looks to be working now.
