### ISSUE TITLE
Espresso.munki ditto: Couldn't read PKZip signature

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/homebysix-recipes#174]
Having an issue running this recipe lately, it downloads but fails to decompress. Not sure if you have seen this before but figured I would report it. 

`Error in local.munki.Espresso: Processor: Unarchiver: Error: Unarchiving /Users/--------/Espresso.zip with ditto failed: ditto: Couldn't read PKZip signature`

**Comment by vmgstudio520** [comment]
Still having the same issue with this recipe.

**Comment by homebysix** [comment]
@jonbrown21 and @vmgstudio520 - Give it another try now. I just updated the download recipe.
