### ISSUE TITLE
Zoom pkg error

### ISSUE THREAD

**Issue by beatlemike** [autopkg/homebysix-recipes#180]
error on script 

`~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/Zoom/Zoom7zUnarchiver.py`

**Comment by mpanighetti** [comment]
Full error message (minus `$CACHE_DIR` paths):

> Error in com.github.homebysix.pkg.Zoom: Processor: Unarchiver: Error: Unarchiving $CACHE_DIR/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip with ditto failed: ditto: $CACHE_DIR/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip: No such file or directory

Looking at [the vendor package that gets downloaded](https://zoom.us/client/latest/ZoomInstallerIT.pkg), it appears that it no longer has a Scripts directory at the expected file path. I don't have access to an older installer so I can't tell if that file has been moved or if the recipe simply doesn't need to perform the associated action anymore.

**Comment by mpanighetti** [comment]
Ah, looks like #177 will address this issue once it's reviewed and merged.

**Comment by mpanighetti** [comment]
This is likely a duplicate of the issue reported in #173.

**Comment by beatlemike** [comment]
Ah loooks like it, thanks
