### ISSUE TITLE
Zoom.pkg.recipe error

### ISSUE THREAD

**Issue by kitzy** [autopkg/homebysix-recipes#186]
Error in com.github.homebysix.pkg.Zoom: Processor: Unarchiver: Error: Unarchiving /Users/kitzy/Library/AutoPkg/Cache/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip with ditto failed: ditto: /Users/kitzy/Library/AutoPkg/Cache/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip: No such file or directory

**Comment by homebysix** [comment]
This might be a duplicate of https://github.com/autopkg/homebysix-recipes/issues/173?

**Comment by homebysix** [comment]
I've merged #177, which should solve this issue.
