### ISSUE TITLE
Skim.download fails code signature verification

### ISSUE THREAD

**Issue by cdbeard** [autopkg/homebysix-recipes#190]
Hello, just a small one, the certificate root for Skim has changed. Updating it with the results of `codesign --display -r- Skim.app` makes the download recipe work again.

**Comment by homebysix** [comment]
Would one of you mind submitting a PR for the change? Otherwise I may get to it later.

**Comment by homebysix** [comment]
The developer went back to the expected signing certificate, so this recipe is working again.
