### ISSUE TITLE
FR: ZoomPresence.download.recipe doesn't append version number to pkg

### ISSUE THREAD

**Issue by kitzy** [autopkg/homebysix-recipes#191]
Alternatively, a separate pkg recipe would be fine too.

I tried writing one myself, but the Zoom pkg seems overly complex and it's a bit over my head.

**Comment by homebysix** [comment]
Give [this recipe](https://github.com/autopkg/homebysix-recipes/blob/a6714188fb9d390fd62690a0e4db2c3116ec2f84/Zoom/ZoomPresence.pkg.recipe) a try and let me know whether that works for you.

**Comment by kitzy** [comment]
@homebysix I love you.
