### ISSUE TITLE
InkScape.munki No Match found on URL 

### ISSUE THREAD

**Issue by roodavis** [autopkg/homebysix-recipes#197]
No match found on URL: https://inkscape/org/en/release/0.92.3/mac-os-x when trying to download latest version.

**Comment by homebysix** [comment]
It looks like there's no Mac package for the latest Inkscape version, according to the [developer's website](https://inkscape.org/release/inkscape-0.92.3/mac-os-x/dl/). If and when that changes, the download recipe should pick it up. In any case, the munki recipe is working as expected.
