### ISSUE TITLE
SnapGeneVieuwer error -> No match found on URL: http://www.snapgene.com/products/snapgene_viewer/

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/homebysix-recipes#198]
Processing SnapGeneViewer.munki...
WARNING: SnapGeneViewer.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
No match found on URL: http://www.snapgene.com/products/snapgene_viewer/
Failed.

The following recipes failed:
    SnapGeneViewer.munki
        Error in com.github.homebysix.munki.SnapGeneViewer: Processor: URLTextSearcher: Error: No match found on URL: http://www.snapgene.com/products/snapgene_viewer/

Nothing downloaded, packaged or imported.

**Comment by homebysix** [comment]
Resolved by #196.
