### ISSUE TITLE
BitTorrent Sync recipe download link is still pointing to v1 app when v2 has been out for a bit

### ISSUE THREAD

**Issue by fseesink** [autopkg/homebysix-recipes#2]
You just helped me resolve an issue with AutoPkgr, and now I see you are the author of several recipes that I DO in fact use, one of them the BitTorrent Sync (BTSync) recipe.  First, thank you for that, and for all you have done.  You have helped me tremendously save time in managing several systems.

Now I'm hoping I can possibly return the favor.  Regarding BTSync, as it stands right now, that recipe is still pulling the old v1 app.  I don't know if that's on purpose or not, but thought I'd ask whether you planned to either update this recipe or provide another for BTSync v2 which came out a few months back.  Looking on their new site for the app (www.getsync.com), it would appear that while the old link you have in BitTorrentSync.download.recipe is effectively

http://download-new.utorrent.com/endpoint/btsync/os/osx/track/stable/BitTorrentSync.dmg

the new download link is

https://download-cdn.getsyncapp.com/stable/osx/BitTorrent-Sync.dmg

indicating both a different URL and filename.

**Comment by homebysix** [comment]
Thanks for the suggestion!
