### ISSUE TITLE
Google Chat pkg recipe generates a package that produces an unusable Chat.app

### ISSUE THREAD

**Issue by SeanHansell** [autopkg/homebysix-recipes#203]
com.github.homebysix.pkg.GoogleChat runs successfully, but the app it drops in the Applications folder cannot be opened. Tested on macOS Mojave. Gathering testing data for other OS's. More to come...
![screenshot 2019-03-01 06 51 19](https://user-images.githubusercontent.com/9552880/53653052-6f798180-3bee-11e9-9f9d-1380e7882a33.png)

**Comment by SeanHansell** [comment]
Confirmed problem in High Sierra as well.

Also confirmed using just the download parent recipe and installing manually works fine.

**Comment by homebysix** [comment]
Thanks for the report! The culprit was the Electron framework permissions. Hopefully it'll be fixed in a subsequent release. In the meantime I've added a postinstall script that sets the permissions correctly.
