### ISSUE TITLE
Parallels Desktop 14

### ISSUE THREAD

**Issue by eshirk** [autopkg/homebysix-recipes#207]
Any chance that support for Parallels Desktop 14 might be in the works? 

Many thanks--

Beth

**Comment by homebysix** [comment]
Hi Beth! My Parallels recipes are built with a `MAJOR_VERSION` input variable that is meant to be overridden with your preferred value. Try changing that to 14 in your local override, and I think you'll get the version you want.

At some point I'll probably update my recipes to 14 by default, so people who newly add the recipes are already on the latest. Thanks!

**Comment by eshirk** [comment]
Wow--thanks for the speedy reply, and sorry I missed that. I'll give it a shot.
