### ISSUE TITLE
Getting chat cannot be opened: check with the developer to make sure Chat works with this version of MacOS

### ISSUE THREAD

**Issue by mikecalbreeeezy** [autopkg/homebysix-recipes#210]
Hello,

Looks like Google released a new chat app version 19.3.141. I added the new pkg file to JSS and added the post install script and getting this error still. Any ideas on how to get it to work?

**Comment by homebysix** [comment]
The pkg recipe _includes_ the postinstall script, so there's no reason to add the postinstall separately to Jamf. Have you updated your repo to make sure the new changes from b0335e4e0c59fd1a7b5948995c3131ec52c236dc are included?

**Comment by mikecalbreeeezy** [comment]
I deleted the postinstall script and updated the repo. I am still getting
that error message.

**Comment by mikecalbreeeezy** [comment]
Not too sure if there was a solution but I updated the repo and added the new Google Hangouts chat .pkg file to JAMF but still getting the error that it is not compatible with my version of MacOs.

**Comment by homebysix** [comment]
I'm not able to reproduce this issue. Chat 19.9.101 installs and launches successfully for me from the pkg recipe.
