### ISSUE TITLE
Update Apache Directory Studio to latest version 2.0.0.v20180908-M14

### ISSUE THREAD

**Issue by hugo4711** [autopkg/homebysix-recipes#214]
Please update Apache Directory Studio to the latest version. Thanks!

**Comment by homebysix** [comment]
Hi @hugo4711 - I'm waiting for some feedback on a related pull request: https://github.com/autopkg/homebysix-recipes/pull/188

If we have to manually update the AutoPkg recipe for each new version of Apache Directory Studio, that defeats the purpose of AutoPkg.

**Comment by hugo4711** [comment]
Yeah, I agree - thanks for keeping me updated!

**Comment by homebysix** [comment]
Resolved in https://github.com/autopkg/homebysix-recipes/pull/188, and currently downloading 2.0.0.v20200411-M15 as expected.
