### ISSUE TITLE
RingCentral.munki should use an installs array

### ISSUE THREAD

**Issue by erikng** [autopkg/homebysix-recipes#227]
The RingCentral package is pretty horrible and doesn't leave the package receipt when installed, so without an installs array munki will not know when to upgrade (say a managed_update) or will worse, infinitely loop the install.

**Comment by homebysix** [comment]
Forgot to close this, but I think it's resolved by https://github.com/autopkg/homebysix-recipes/commit/26d0617b240ec391482adb4424fea42985b53bd6#diff-4ede346916eee8b8f219eb42a0153d60.
