### ISSUE TITLE
JSSImporter.install duplication and pkg name

### ISSUE THREAD

**Issue by grahampugh** [autopkg/homebysix-recipes#251]
Hi @homebysix 

Just researching a presentation and looking for the definitive JSSImporter recipe. I can see two, yours and @rtrouton 's. They are almost identical, save only for the fact that Rich's names the package with a version, whereas yours just calls it `JSSImporter.pkg`. 

(I also have `JSSImporterBeta.install` which may no longer serve a purpose, so I will think about whether retire this soon).

I'm ambivalent as to which recipe should be kept, but perhaps we should retire one.

**Comment by homebysix** [comment]
I like having a version in the package name, so I'd be happy to deprecate mine in favor of Rich's.

**Comment by rtrouton** [comment]
Meanwhile, I entirely forgot I had that recipe. 😂 . Still, that works fine for me as well.

**Comment by grahampugh** [comment]
So @rtrouton's recipe gets the conference mention :) Thanks both.
