### ISSUE TITLE
GoToMeeting.download.recipe returns SSL error and fails to download

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/homebysix-recipes#262]
Hey, 

I'm not sure if this is an issue with the custom processor (GoToMeetingURLProvider.py) of GoToMeeting themselves, but running the .download recipe results in the below error:

`Processor: URLDownloader: Error: Curl failure: LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54 (exit code 56) `

If I try a GUI Safari download of the discovered URL (https://bbuilds.getgocdn.com/builds/g2m/15911/G2M_Mac_x86) the ~30MB seems to stall after a while and stopping progressing.

I'm afraid my Python skills are lacking and I'm not able to purse the troubleshooting much further.

Any thoughts, or suggestions I could try?

**Comment by homebysix** [comment]
I can't reproduce this issue on macOS 10.14.6 with AutoPkg 1.4.1 and Python 2.7.16.  Looks like it might be related to an underlying tool, rather than the recipe itself. (https://github.com/autopkg/apettinen-recipes/issues/4)

Does the same issue occur for you on a different Mac or OS version?

**Comment by Daz-wallace** [comment]
Strange, this now seems to be working fine for me.

Oh well ¯\_(ツ)_/¯ 😊
