### ISSUE TITLE
Deltopia DeltaWalker: installed app will not run

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/homebysix-recipes#273]
While the recipe will install the app, DeltaWalker will close immediately when opened.
There seems to be a file/files missing that decompresses the contained Java libraries.
I compared this to the DMG from the developer's website, which installs the app correctly.

**Comment by homebysix** [comment]
I'm not able to reproduce this with AutoPkg 1.4.1 on macOS 10.14.6.

Are you installing the app from the pkg recipe or the install recipe?

**Comment by workflowsguy** [comment]
After removing all traces of the old version and installing the latest version through my override of your .munki recipe, the app runs now.

Apologies for raising a false alarm!
