### ISSUE TITLE
ChronoSync.download mismatch in authority names

### ISSUE THREAD

**Issue by Bupsy** [autopkg/homebysix-recipes#286]
Hello,

The ChronoSync.download recipe is failing due to a mismatch in the authority names, the expected authority does not include their team ID:

> CodeSignatureVerifier: Mismatch in authority names
> CodeSignatureVerifier: Expected: Developer ID Installer: Econ Technologies, Inc. -> Developer ID Certification Authority -> Apple Root CA
> CodeSignatureVerifier: Found:    Developer ID Installer: Econ Technologies, Inc. (9U697UM7YX) -> Developer ID Certification Authority -> Apple Root CA

**Comment by homebysix** [comment]
Thanks for letting me know!
