### ISSUE TITLE
Curl timeout with GoToMeeting.download.recipe

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/homebysix-recipes#296]
Hi, 

To be totally honest, I'm not full sure if this is an issue with the vender or the URL the recipe builds for the download! The URL that's pumped into URLDownloader (https://bbuilds2.getgocdn.com/builds/g2m/17052/G2M_Mac_x86) will fail with a curl exit code of 28, which I believe is a timeout. 

The same URL times out when used in Safari so it's looking like the vender or the download URL are the issue. I'm afraid my Python skills are a little too lacking to pull apart the custom processor, and the vender's site seems to allow downloads ok.

Let me know if I can be of more any help!

**Comment by homebysix** [comment]
Maybe this is something that was fixed on the vendor side. Running the recipe now gets me a different URL (https://bbuilds2.getgocdn.com/builds/g2m/17359/G2M_Mac_x86) and finishes successfully.
