### ISSUE TITLE
Cocktail 14

### ISSUE THREAD

**Issue by echoparkbaby** [autopkg/homebysix-recipes#298]
Cocktail download link not working. 
    Cocktail-10.14.munki.recipe
        Error in local.munki.14.Cocktail-10: Processor: SparkleUpdateInfoProvider: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://www.maintain.se/downloads/sparkle/mojave/mojave.xml']' returned non-zero exit status 60.

**Comment by homebysix** [comment]
Hi @echoparkbaby - Could you try again after updating the repo? I couldn't replicate your issue, but I made a change in 925a398 to fix another issue with the Mojave Cocktail recipe.

**Comment by echoparkbaby** [comment]
Hi Elliot! That fixed it :) It's now downloading version 12.5. cool beans.
thanks so much
best,
Brandon



BRANDON WALTER
Mac Consultant | www.macfaqulty.com
bw@macfaqulty.com | 310-435-9972
