### ISSUE TITLE
How can an override prevent Extension Attributes from being made?

### ISSUE THREAD

**Issue by adam-koho** [autopkg/homebysix-recipes#301]
I created an override for `Skype.jss.recipe` as `Skype-selfservice.jss.recipe`. Whenever I run the override, it always create a Extension Attributes (EA) `Skype` on my Jamf Pro. `Zoom.jss.recipe` also create the same EA. I just want to get rid of those EAs.
I added an empty string to the following key in the override, but it doesn't work.
```
<dict>
	<key>extension_attributes</key>
	<string></string>
</dict>
```

**Comment by homebysix** [comment]
This issue might be better opened in the [jss-recipes](https://github.com/autopkg/jss-recipes) or [JSSImporter](https://github.com/jssimporter/JSSImporter) repo. However, the answer is going to involve creating a duplicate recipe (and corresponding override) that lacks a `extension_attributes` [key/value](https://github.com/autopkg/jss-recipes/blob/master/Skype/Skype.jss.recipe#L45-L51) in the JSSImporter processor arguments.
