### ISSUE TITLE
CodeSignatureVerifier: Error: Code signature verification failed

### ISSUE THREAD

**Issue by everetteallen** [autopkg/homebysix-recipes#32]
Just wanted to let you know that I am getting the error below when using the child R recipe from autopkg/jss-recipes.  I am using an override but I did not see a way to set DISABLE_CODE_SIGNATURE_VERIFICATION in an override.
Thanks!

Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1459, in run_recipes autopackager.process(recipe) File "/Library/AutoPkg/autopkglib/__init__.py", line 479, in process % (identifier, step["Processor"], unicode(err))) AutoPackagerError: Error in local.jss.UNCWide-AutoPKG-R: Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

**Comment by homebysix** [comment]
@everetteallen Good catch, it does indeed fail. R-3.2.3 is not a signed package. However, it looks like R-3.2.0, R-3.2.1, and R-3.2.2 were signed packages:

![3 2 0](https://cloud.githubusercontent.com/assets/7801391/11750106/80f63b94-9fe6-11e5-8d93-8b3848ed8f5e.png)
![3 2 1](https://cloud.githubusercontent.com/assets/7801391/11750110/85a33192-9fe6-11e5-9ffd-64c9aa36c8f2.png)
![3 2 2](https://cloud.githubusercontent.com/assets/7801391/11750116/89ba97ca-9fe6-11e5-94f4-3e74b8f477c2.png)

Therefore, I can only assume that this is either a oversight in the release process or a temporary situation, and will probably be fixed for 3.2.4.

If 3.2.4 is released without a signed package, I'll remove the CodeSignatureVerifier processor from the download recipe. Until then, you can use an override like this one to disable code signature verification:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.download.R</string>
	<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>R</string>
		<key>DISABLE_CODE_SIGNATURE_VERIFICATION</key>
		<string>true</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.homebysix.download.R</string>
</dict>
</plist>
```

**Comment by everetteallen** [comment]
I was able to add the key to the input section of my override and suppress the error.
However this recipe will not override the name as reported with the Yo recipe earlier.
Should I make a separate issue?

**Comment by homebysix** [comment]
@everetteallen Yes, go ahead and make a separate issue for the name override thing. I'm not sure exactly what you mean, but I don't think it's related to code signature verification.

I'll keep this issue open in order to remind me to check code signature verification when 3.2.4 comes out:
https://cran.r-project.org/bin/macosx/

**Comment by homebysix** [comment]
R 3.2.4 is out and it's properly signed.
