### ISSUE TITLE
VyprVPN.download.recipe pulling version 3.X - new version is 4.X

### ISSUE THREAD

**Issue by rodgerramjet26** [autopkg/homebysix-recipes#326]
This looks to be because the download page has changed to https://www.vyprvpn.com/vpn-apps/vpn-for-mac.

Having a quick look at the recipe I think just changing the download page URL might fix the issue.

**Comment by homebysix** [comment]
When I go to the page you linked above and click Download, I still get version 3. However, I found that this page links to version 4: https://www.vyprvpn.com/vpn-apps/vpn-for-mac-matrix
