### ISSUE TITLE
Replacement of Papers Recipe

### ISSUE THREAD

**Issue by qu1gl3s** [autopkg/homebysix-recipes#331]
The Papers license in this repository is for version 3 which is no longer being actively sold by Readcube and whose last update was October 2019.

With Readcube moving to their new application, version 4 with a different deployment mechanism, I'd like to request the replacement or deprecation of this recipe for a newer version.

With help from the #autopkg channel on the MacAdmins Slack, I believe I have written a suitable replacement for use by the AutoPkg community which can be located here: [https://github.com/qu1gl3s/qu1gl3s-recipes/tree/master/Papers](https://github.com/qu1gl3s/qu1gl3s-recipes/tree/master/Papers)

**Comment by homebysix** [comment]
Hi @qu1gl3s - Thanks for the heads up. Are you suggesting I deprecate my recipes, or adopt yours?

**Comment by homebysix** [comment]
A pull request that replaces the version 3 Sparkle feed with the version 4 Sparkle feed (or URLTextSearcher equivalent) would be welcome.
