### ISSUE TITLE
Zom.munki no longer works - verbose output below

### ISSUE THREAD

**Issue by bubba-maker** [autopkg/homebysix-recipes#333]
% autopkg run -v Zoom.munki
Processing Zoom.munki...
WARNING: Zoom.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/downloads/Zoom.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Zoom.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2020-09-21 03:54:47 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Zoom Video Communications, Inc. (BJ4HAAB9B3)
CodeSignatureVerifier:        Expires: 2022-04-05 23:42:49 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            36 AF C6 B4 4F F0 68 FD 67 40 AC D2 80 F6 6E B7 82 D1 08 E8 15 22
CodeSignatureVerifier:            EC 3B 2F 57 6E BA 90 AC 62 BC
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
PkgRootCreator
PkgRootCreator: Created /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/Zoom
PkgRootCreator: Created /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/Zoom/Applications
FlatPkgUnpacker
FlatPkgUnpacker: Unpacked /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/downloads/Zoom.pkg to /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/expanded
PkgPayloadUnpacker
PkgPayloadUnpacker: Unpacked /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/expanded/zoomus.pkg/Payload to /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/Zoom/Applications/zoom.us.app
Versioner
File '/Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/Zoom/Applications/zoom.us.app/Contents/Info.plist' does not exist or could not be read.
Failed.
Receipt written to /Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/receipts/Zoom-receipt-20200921-092533.plist

The following recipes failed:
    Zoom.munki
        Error in com.github.homebysix.munki.Zoom: Processor: Versioner: Error: File '/Users/bubba-maker/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/Zoom/Applications/zoom.us.app/Contents/Info.plist' does not exist or could not be read.

Nothing downloaded, packaged or imported.

**Comment by UGAmatt** [comment]
I was investigating this issue on my own. Due to what I would surmise is a change in the way that Zoom packages their IT installer, the autopkg recipe is creating a package that nests the zoom application bundle inside of itself.

Changing the destination_path for the PkgPayloadUnpacker to remove the trailing 'zoom.us.app/' from the path addressed the issue for me.

I don't know if that will be a durable fix though since I'm not sure about what exactly changed that caused the issue to arise in the first place.

**Comment by homebysix** [comment]
Hi @bubba-maker - Could you `repo-update` and try again? Should be resolved by https://github.com/autopkg/homebysix-recipes/pull/334.

**Comment by bubba-maker** [comment]
That change fixed my issue!  Thank you!!
