### ISSUE TITLE
zoom-pkg recipe no longer working

### ISSUE THREAD

**Issue by raymondlyon** [autopkg/homebysix-recipes#335]
Today I got an error in autopkg saying that the index.plist file could not be found within zoom.us.app. Examining the download directory, I can see that there is a zoom.us.app within zoom.us.app, so the path does not work right. Screenshots below:

<img width="420" alt="Screen Shot 2020-09-21 at 12 23 18 PM" src="https://user-images.githubusercontent.com/53532529/93794069-a1ee3380-fc05-11ea-97fe-fa30d2237c7d.png">

<img width="464" alt="Screen Shot 2020-09-21 at 12 25 02 PM" src="https://user-images.githubusercontent.com/53532529/93794082-a581ba80-fc05-11ea-96e7-fbe26538ba31.png">

Obviously the quick workaround would be to change the path in the recipe, but I'm not sure why this is happening in the first place. Let me know if I can provide any more helpful information.

Thank you!

**Comment by raymondlyon** [comment]
Closing since this is a duplicate of #333

**Comment by dcoobs** [comment]
See #333
