### ISSUE TITLE
Zoom.us Munki recipe error (Output below)

### ISSUE THREAD

**Issue by matt-a-new** [autopkg/homebysix-recipes#357]
I seem to be running into an error when trying to use the Zoom.munki recipe:

<img width="423" alt="Screen Shot 2020-12-14 at 2 34 45 PM" src="https://user-images.githubusercontent.com/76016429/102144264-0c37fe00-3e1a-11eb-8a10-1c81afbb78da.png">

**Comment by homebysix** [comment]
Do you have the parent recipes for those recipes cloned locally? Keep in mind a recipe's parent may not be in the same repo as the recipe itself. AutoPkgr's read me "troubleshooting" section contains some details that may be helpful.

**Comment by matt-a-new** [comment]
Thanks was able to resolve with your comment info.
