### ISSUE TITLE
FYI: GoToMeeting.dmg seems to be generally be available

### ISSUE THREAD

**Issue by jgstew** [autopkg/homebysix-recipes#389]
I don't know if this is always reliable, but I was looking at `https://builds.cdn.getgo.com/g2mupdater/live/config.json` as used by https://github.com/autopkg/homebysix-recipes/blob/master/GoToMeeting/GoToMeetingURLProvider.py#L36

and there is this line:

`"macDownloadUrlTemplate": "https://bbuilds2.getgocdn.com/builds/g2m/%build%/G2M_Mac_x86"`

but it seems like there is usually a DMG available for download given by:

`https://bbuilds2.getgocdn.com/builds/g2m/%build%/GoToMeeting.dmg`

Current example:

`https://builds.cdn.getgo.com/builds/g2m/19228/GoToMeeting.dmg`

This seems like a way to potentially save steps in the recipe.

Not sure if there is a specific reason to NOT use the DMG there, or if the current method is just for historical reasons.

**Comment by jgstew** [comment]
A minor thing, but I noticed that the code that gets the maximum build number for GoToMeeting depends on the order of the build numbers in the array within the JSON, not by getting all build number integers, then getting the maximum. This will continue to work as long as the JSON is formatted consistently with the newest build number at the end, but not a certainty.

https://github.com/autopkg/homebysix-recipes/blob/master/GoToMeeting/GoToMeetingURLProvider.py#L91

**Comment by homebysix** [comment]
Thanks! I agree that the disk image would help to reduce the number of steps. However, right now my testing is hindered by a certificate error:

![image](https://user-images.githubusercontent.com/7801391/113487099-e5561400-946a-11eb-89e5-4f0376f5d911.png)

Hopefully that's temporary and I can merge the changes soon. In the meantime, the changes are in [this branch](https://github.com/homebysix/homebysix-recipes/tree/gotomeeting-dmg), if you'd like to test.

**Comment by jgstew** [comment]
lol, now I feel like all multi-year SSL certs should expire April 1st.
