### ISSUE TITLE
A Possible Bug in Zoom.pkg Postscript for Big Sur

### ISSUE THREAD

**Issue by UGAmatt** [autopkg/homebysix-recipes#391]
One of my co-workers noted today that the audio driver for Zoom was not being installed properly for Big Sur clients when using the package generated by the Zoom.pkg recipe.

Looking at [the postscript itself](https://github.com/autopkg/homebysix-recipes/blob/master/Zoom/scripts/postinstall), it appears to me that the issue is with line 42. The code looks for a minor version higher than 9. However, in Big Sur, the major version is now 11 and the minor version is whatever dot-release is installed. Thus, the driver install is being skipped entirely for all extant Big Sur versions.

My shell scripting is admittedly a bit weak, but I think replacing the existing line 42 with:
`if [ "$minorver" -gt 9 -o "$majorver" -gt 10]; then`
would be a sufficient fix?

**Comment by jgstew** [comment]
It is odd to me that `if [ "$minorver" -gt 9 ]; then` shows up twice in there too.

https://github.com/autopkg/homebysix-recipes/blob/master/Zoom/scripts/postinstall#L58

**Comment by homebysix** [comment]
I adjusted the script (#392) to align with the behavior in Catalina.

I know @ygini created the script based on a script in the vendor's installer, and it's likely that the vendor script has diverged from the one in this repo.
