### ISSUE TITLE
Vienna.download recipe fails

### ISSUE THREAD

**Issue by oliverweinm** [autopkg/homebysix-recipes#425]
The recipe fails with the following error in the URLDownloader processor:

SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://viennarss.github.io/sparkle-files/changelog.xml'}}
SparkleUpdateInfoProvider: Version retrieved from appcast: 7437
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 3.7.1 :d356d926:
SparkleUpdateInfoProvider: Found URL https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz
{'Output': {'url': 'https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz',
            'version': '3.7.1 :d356d926:'}}
com.github.homebysix.VersionSplitter/VersionSplitter
{'Input': {'version': '3.7.1 :d356d926:'}}
VersionSplitter: Split version: 3.7.1
{'Output': {'version': '3.7.1'}}
URLDownloader
{'Input': {'filename': 'Vienna-3.7.1.tgz',
           'url': 'https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 177, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz', '--fail', '--output', '/Users/setup/Library/AutoPkg/Cache/com.github.homebysix.download.Vienna/downloads/tmpp23331xu']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 326, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 185, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 180, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz', '--fail', '--output', '/Users/setup/Library/AutoPkg/Cache/com.github.homebysix.download.Vienna/downloads/tmpp23331xu']' returned non-zero exit status 22.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz', '--fail', '--output', '/Users/setup/Library/AutoPkg/Cache/com.github.homebysix.download.Vienna/downloads/tmpp23331xu']' returned non-zero exit status 22.
Failed.
Receipt written to /Users/setup/Library/AutoPkg/Cache/com.github.homebysix.download.Vienna/receipts/com.github.homebysix.download-receipt-20210517-035032.plist

My suspicion is, is that the error occurs due to the SparkleUpdateInfoProvider returning a non-valid URL as an output. In my testing the URL returned by the SparkleUpdateInfoProvider is "https://github.com/ViennaRSS/vienna-rss/releases/download/v%252F3.7.1/Vienna3.7.1.tar.gz", which cannot be found.

**Comment by homebysix** [comment]
Should be fixed now by #429. The problem was that the Sparkle feed was providing a quoted enclosure URL, which was then being quoted again unnecessarily during AutoPkg's processing.
