### ISSUE TITLE
r.munki stops working -> Mismatch in authority names

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/homebysix-recipes#427]
r.munki works till version 4.0.5

Version 4.1.0 is released (18-05-2021) and stops working.

R.munki...
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
 
The following recipes failed:
    R.munki
        Error in local.munki.R: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
 
Nothing downloaded, packaged or imported.

**Next I did this:** 

autopkg run -k DISABLE_CODE_SIGNATURE_VERIFICATION=1  R.munki
Processing R.munki...
 
The following new items were imported into Munki:
    Name  Version  Catalogs  Pkginfo Path          Pkg Repo Path       Icon Repo Path  
    ----  -------  --------  ------------          -------------       --------------  
    R     3.3.3    pretest   apps/R/R-3.3.3.plist  apps/R/R-3.3.3.pkg    

**It downloads an old version**

**If i run it again:**

autopkg run R.munki
Processing R.munki...
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
 
The following recipes failed:
    R.munki
        Error in local.munki.R: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
 
Nothing downloaded, packaged or imported.

**Comment by homebysix** [comment]
Should be fixed by #430. The issue wasn't with the code signature verification, but rather that the regex pattern needed to be updated to grab R-4.1.0.pkg, which has the expected code signature.
