### ISSUE TITLE
purpose of kubectl custom installcheck_script ?

### ISSUE THREAD

**Issue by octomike** [autopkg/homebysix-recipes#431]
We just tried to import the kubectl package and the installcheck_script seems to be broken and unnecessary. The [docs](https://github.com/munki/munki/wiki/How-Munki-Decides-What-Needs-To-Be-Installed#install-check-script) state that:

> An "installcheck_script" should be crafted such that an exit code of 0 indicates that the item is currently not installed and should therefore be installed. All non-zero exit codes indicate that the item in question is installed.

There is:

```python
kubectl = "/usr/local/bin/kubectl"
offered_version = "%version%"
      
if not os.path.isfile(kubectl):
    sys.exit(1)
[...]
```

1. The return values seem switched? This should return 0, right?
2. Why is it there at all? The pkg comes with a proper pkg receipt and seems installable/uninstallable fine without the script.

**Comment by homebysix** [comment]
You're right — I suspect I wrote this specifically to support patching existing installs (which may or may not have the package receipt). A more Munki-like approach would be to simply use the package receipt. I'll make that change.
