### ISSUE TITLE
FuzzMeasure - URLTextSearcher: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'https://www.rodetest.com/download']' returned non-zero exit status 60.

### ISSUE THREAD

**Issue by macmule** [autopkg/homebysix-recipes#437]
FYI, https://www.rodetest.com/download isn't accessible right now.

Not sure if a temp issue etc, but raising for awareness.

**Comment by homebysix** [comment]
Looks like an expired certificate. Hopefully the developer will fix soon.

![image](https://user-images.githubusercontent.com/7801391/122796671-82a73400-d273-11eb-9433-d8ee346f0399.png)

**Comment by macmule** [comment]
indeed, working now,
