### ISSUE TITLE
Papers Recipe not locating download

### ISSUE THREAD

**Issue by ljcacioppo** [autopkg/homebysix-recipes#441]
When running the Papers recipe, I am met with the following error:

"No match found on URL: https://update.readcube.com/desktop/updates/latest-mac.yml"

In looking at the recipe, I am not certain this is the case, but it looks like maybe the name of the package has now changed to include "-x64" at the end, as if I remove the "-x64" from the dmg name, it does appear to match the regex pattern

**Comment by homebysix** [comment]
Resolved by https://github.com/autopkg/homebysix-recipes/pull/442
