### ISSUE TITLE
ParallelsDesktop Version 17

### ISSUE THREAD

**Issue by WiesBen** [autopkg/homebysix-recipes#455]
Override with ARCH "image" and Major Version 17 is working. But when trying to install, there is nothing installed. No .app in Applications folder or other things. 

Is there a way to debug it?

**Comment by homebysix** [comment]
Hi @WiesBen - You haven't given me much to go on here. I assume you're running my `ParallelsDesktop.install.recipe`? Can you provide some output from `autopkg run -vv`?

Also, maybe you simply shortened the names for brevity, but the override variables you should be using are `PLATFORM_ARCH` and `MAJOR_VERSION`. Using `ARCH` will not work.

**Comment by homebysix** [comment]
Thanks for the details, that helps.

Trying a hunch... if you press `Cmd-Shift-period` while in the Applications folder, does the Parallels Desktop.app appear? If so, the postinstall script `chflags nohidden` command might be failing for some reason.

**Comment by homebysix** [comment]
Hi @WiesBen - Could you share the output of this command?

```
mdfind "kMDItemCFBundleIdentifier == 'com.parallels.desktop.console'"
```

My theory is that Parallels is being detected and "upgraded" at a different path than /Applications.
