### ISSUE TITLE
Eclipse.munki errors

### ISSUE THREAD

**Issue by jby** [autopkg/homebysix-recipes#465]
```
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://eclipse.org/downloads/download.php?r=1&file=/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-macosx-cocoa-x86_64.dmg', '--fail', '--output', '/Users/jonasb/Library/AutoPkg/Cache/local.munki.Eclipse/downloads/tmp3h8itzh0', '--header', 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.39 (KHTML, like Gecko) Version/9.0 Safari/601.1.39', '--header', 'If-None-Match: "14055298-5cbf77699df7d"', '--header', 'If-Modified-Since: Tue, 14 Sep 2021 16:56:30 GMT']' returned non-zero exit status 52.
Failed.

The following recipes failed:
    local.munki.Eclipse
        Error in local.munki.Eclipse: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://eclipse.org/downloads/download.php?r=1&file=/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-macosx-cocoa-x86_64.dmg', '--fail', '--output', '/Users/jonasb/Library/AutoPkg/Cache/local.munki.Eclipse/downloads/tmp3h8itzh0', '--header', 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.39 (KHTML, like Gecko) Version/9.0 Safari/601.1.39', '--header', 'If-None-Match: "14055298-5cbf77699df7d"', '--header', 'If-Modified-Since: Tue, 14 Sep 2021 16:56:30 GMT']' returned non-zero exit status 52.

Nothing downloaded, packaged or imported.
```

**Comment by homebysix** [comment]
I can't reproduce this issue. The dmg downloads as expected for me.

What do you get when you take AutoPkg out of the equation and run this: `curl -sIL 'https://eclipse.org/downloads/download.php?r=1&file=/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-macosx-cocoa-x86_64.dmg'`

According to [this page](https://everything.curl.dev/usingcurl/returns) the exit status 52 indicates something wrong on the server's end, so trying again later might be the solution.

**Comment by jby** [comment]
Ok - somehow it works when manually downloading with `wget` but not with `curl`.
Apparently it's a redirect (HTTP 302 Found) and wget follows that but curl doesn't, for some reason.

**Comment by homebysix** [comment]
The way AutoPkg uses `curl` should allow redirects to be followed (see [URLGetter.py](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLGetter.py#L54)). But I'm running AutoPkg 2.3.1 and don't get the URLDownloader error you're seeing.

**Comment by jby** [comment]
It was probably server-related, it's gone now.

**Comment by jby** [comment]
And now it's back, though this time with exit status 16 instead...
