### ISSUE TITLE
Wrong %NAME% when running KeyboardMaestro.munki

### ISSUE THREAD

**Issue by AndersTao** [autopkg/homebysix-recipes#47]
Running KeyboardMaestro.munki.recipe using KeyboardMaestro.download.recipe as parent recipe, CodeSignatureVerifier fail's because %NAME% is used as "KeyboardMaestro" and not as "Keyboard Maestro"

Joining the 2 in to 1 munki.recipe, with no parents works!, but not a good solution.

It my look as an Autopkg problem, don't know!?

Error:
`CodeSignatureVerifier: /Users/Shared/AutoPkg/Cache/com.github.homebysix.munki.KeyboardMaestro/KeyboardMaestro/Applications/KeyboardMaestro.app: No such file or directory
Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.`

Works:
`CodeSignatureVerifier
CodeSignatureVerifier: Verifying application bundle signature...
CodeSignatureVerifier: /Users/Shared/AutoPkg/Cache/com.github.homebysix.download.km-test/Keyboard Maestro/Applications/Keyboard Maestro.app: valid on disk
CodeSignatureVerifier: /Users/Shared/AutoPkg/Cache/com.github.homebysix.download.km-test/Keyboard Maestro/Applications/Keyboard Maestro.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/Shared/AutoPkg/Cache/com.github.homebysix.download.km-test/Keyboard Maestro/Applications/Keyboard Maestro.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid`

**Comment by homebysix** [comment]
@AndersTao Running `autopkg run -v KeyboardMaestro.munki` works for me. The `%NAME%` should be `Keyboard Maestro`. Here's the full log of my verbose run: https://gist.github.com/homebysix/e8a30eb22522314ad581

Can you post the contents of your `com.github.homebysix.download.km-test` processor?

**Comment by AndersTao** [comment]
Sure 😊

[https://gist.github.com/AndersTao/8d2ef61f5741624e572f](url)

**Comment by homebysix** [comment]
I split apart your km-test recipe into its download and Munki components, and the only difference between that and my recipes is an [oddly-placed pkginfo dict](https://gist.github.com/AndersTao/8d2ef61f5741624e572f#file-km-test-download-recipe-L108-L124).

Could you run `autopkg run -v KeyboardMaestro.munki` and post the output? Thanks!

I'm updating the recipes with a new download page URL now, but that shouldn't affect this issue.

**Comment by homebysix** [comment]
Interesting. I don't remember ever using `KeyboardMaestro` as the name, so I'm not sure where why a `repo-update` would help. But as long as it's working now, I'll close this issue.

**Comment by AndersTao** [comment]
I see the same problem for PlistEditPro.download

I have done the same changes, as you did for KM, and it works
https://gist.github.com/AndersTao/602de68ca91c8b98890d
