### ISSUE TITLE
Grammarly Recipe

### ISSUE THREAD

**Issue by matt-a-new** [autopkg/homebysix-recipes#484]
Hello

Looks like the Grammarly recipe is failing.  I attempted to visit the URL from the grammarly.download.recipe and getting an "Access Denied":
```
AccessDeniedAccess Denied73YGY9TRZ9GEZDYFF7kAuZq+PjsMttvA9OBPj2ri+xXhq5wEap4HKPCGm6WzPerTyUPTSXG81OcvjH9EDkbu2N4A1Jw=
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>73YGY9TRZ9GEZDYF</RequestId>
<HostId>F7kAuZq+PjsMttvA9OBPj2ri+xXhq5wEap4HKPCGm6WzPerTyUPTSXG81OcvjH9EDkbu2N4A1Jw=</HostId>
...
</Error>
```
May need to update the URL in the parent (grammarly.download.recipe)

**Comment by homebysix** [comment]
Hi @matt-a-new - It looks like Grammarly changed its disk image contents slightly. The app is now called `Grammarly Installer.app` and has a different bundle identifier.

However, upon further inspection it looks like `Grammarly Installer.app` is the exact same app as the one that gets installed to `/Applications/Grammarly Desktop.app` when the installer runs. I've reworked the recipes to copy the former to the latter, and it seems to work in my limited testing.

Could you `repo-update` and `run` again to see if it works for you?

**Comment by matt-a-new** [comment]
@homebysix it looks like it ran ok.  But it just pulled an old verision:
```
Current verision: 1.5.78
Verision after mege: 1.0.0.1
```

**Comment by homebysix** [comment]
You'll have to take that up with Grammarly's release team. Unfortunately, it looks like they reset the app version back to 1.0.0 recently.
