### ISSUE TITLE
Wireshark now offers both x64 and ARM64 binaries starting with v3.6.0

### ISSUE THREAD

**Issue by fseesink** [autopkg/homebysix-recipes#493]
More of a question than an issue.

Currently the Wireshark munki recipes are pulling down the Intel x64 binaries only.  Starting with Wireshark v3.6.0, I noticed they have both x64 and ARM64 specific binaries.

I was just wondering if you intend to add support for the ARM64 binaries?

**Comment by homebysix** [comment]
Hi @fseesink - I just added an `ARCH` input variable to the recipes. You can set this value to `Arm` in order to download the Apple Silicon binary. Thanks!

**Comment by fseesink** [comment]
Cool!  Thanks.

Now just have to figure out how to provide both.  I support both x64 and M1 Macs using Munki.  I know I could just go with x64 and throw the burden on Rosetta, but would be nice to have each platform get their respective versions.  Wondering if I could simply create 2 overrides of the Munki recipe, one for each architecture, and set the `supported_architectures` array accordingly in each.

**Comment by homebysix** [comment]
Yes, that's a good start. The [dev](https://github.com/autopkg/autopkg/tree/dev) branch of AutoPkg has as-yet-unreleased MunkiImporter features that will allow importing packages into Munki with different architectures but the same name/version.
