### ISSUE TITLE
GraphicConverter versioning issue

### ISSUE THREAD

**Issue by grahampugh** [autopkg/homebysix-recipes#504]
I hope this is temporary, but the Sparkle feed for the current version of GraphicConverter (major version 11) is not providing a user-facing version number. Therefore, the appcast version is being supplied instead. Judging by our automation, the current version, 11.5.5, was previously issued with a user-facing version string, as we already have it in production, but it does not anymore. In contrast, the current 10.* version is still providing a user-facing version string.

If this isn't remedied, I suggest that the version string should be extracted from the downloaded app rather than relying on the Sparkle feed for the info.

**Major Version 10**
```
 % autopkg run -v GraphicConverter.download --ignore-parent-trust-verification-errors
Looking for GraphicConverter.download...
Found GraphicConverter.download in recipe map
**load_recipe time: 0.0007531819999999634
Processing GraphicConverter.download...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: 3483
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 10.7.5
SparkleUpdateInfoProvider: Found URL https://www.lemkesoft.info/files/graphicconverter/gc10_build3483.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 14 Dec 2020 09:43:12 GMT
URLDownloader: Storing new ETag header: "a1cbbbf-5b66978704e26"
URLDownloader: Downloaded /Users/gpugh/Library/AutoPkg/Cache/com.github.homebysix.download.GraphicConverter/downloads/GraphicConverter-10.7.5.zip
EndOfCheckPhase
```

**Major Version 11**
```
% autopkg run -v GraphicConverter.download --ignore-parent-trust-verification-errors --key MAJOR_VERSION=11
Looking for GraphicConverter.download...
Found GraphicConverter.download in recipe map
**load_recipe time: 0.0007669160000000064
Processing GraphicConverter.download...
SparkleUpdateInfoProvider
SparkleUpdateInfoProvider: Version retrieved from appcast: build5314
SparkleUpdateInfoProvider: Found URL https://www.lemkesoft.info/files/graphicconverter/gc11_build5314.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 28 Dec 2021 14:09:29 GMT
URLDownloader: Storing new ETag header: "11e089a3-5d4355ea50904"
URLDownloader: Downloaded /Users/gpugh/Library/AutoPkg/Cache/com.github.homebysix.download.GraphicConverter/downloads/GraphicConverter-build5314.zip
EndOfCheckPhase
```

I would also suggest that the default `MAJOR_VERSION` should be updated to match the current version (`11`).

**Comment by homebysix** [comment]
Hi @grahampugh - Thanks for reporting this. Could you try the modifications I made in 041d214 and see if that works for you?

**Comment by grahampugh** [comment]
I was not able to figure out how to checkout the commit you made. But I'm sure adding the Versioner processor will do the trick.

**Comment by homebysix** [comment]
Sorry, it's because it was on my homebysix/homebysix-recipes fork, not the autopkg/homebysix-recipes origin. Merged now, so ready to try.
