### ISSUE TITLE
VirtualBox NAME variable issues

### ISSUE THREAD

**Issue by mikedowler** [autopkg/homebysix-recipes#506]
The VirtualBox recipes encounter a couple of issues if the NAME variable is set to anything other than "VirtualBox":
* The CodeSignatureVerifier processor in the download recipe looks for a .pkg called "%NAME%.pkg" inside the downloaded .dmg.  This .pkg name is determined by Oracle, and so is always called VirtualBox.pkg
* The PkgCopier processor in the pkg recipe outputs to "VirtualBox-%version%.pkg", ignoring whatever value has been set for NAME.  It is a common convention to use NAME when naming a pkg, since this allows the admin (via overrides) to determine the name of the pkg.  In my case, for example, I want to name my pkg "OracleVirtualBox".

Creating a PR to address these issues.

**Comment by homebysix** [comment]
I merged https://github.com/autopkg/homebysix-recipes/pull/507, so this should be fixed. Thank you!
