### ISSUE TITLE
Zoom updates have been separated for m1 and intel

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/homebysix-recipes#508]
https://zoom.us/download

Zoom Client for Meetings has been set up by the vendor to be separate for lintels and m1s.

Can you please update recipes to accommodate for this?

also opened at https://github.com/autopkg/jss-recipes/issues/263

**Comment by homebysix** [comment]
The upstream issue would need to be addressed first: https://github.com/autopkg/hansen-m-recipes/issues/210

**Comment by homebysix** [comment]
Closed upstream — unnecessary due to Zoom's IT Installer being Universal.
