### ISSUE TITLE
Tunnelblick fails to update

### ISSUE THREAD

**Issue by WimDeMeester** [autopkg/homebysix-recipes#51]
A new version of Tunnelblick is available. However, I'm unable to update Tunnelblick. I get the following error message:

`autopkg run -v Tunnelblick.munki.recipe
Processing Tunnelblick.munki.recipe...
URLTextSearcher
No match found on URL: https://tunnelblick.net/downloads.html
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/com.github.homebysix.munki.Tunnelblick/receipts/Tunnelblick.munki-receipt-20160321-115444.plist

The following recipes failed:
    Tunnelblick.munki.recipe
        Error in com.github.homebysix.munki.Tunnelblick: Processor: URLTextSearcher: Error: No match found on URL: https://tunnelblick.net/downloads.html

Nothing downloaded, packaged or imported.`

**Comment by homebysix** [comment]
Hi @WimDeMeester. I think I fixed this in https://github.com/autopkg/homebysix-recipes/commit/531d4deed1d46720fe9631ec41d67331302d2c4c. Can you update and try again?

**Comment by WimDeMeester** [comment]
Works perfect! Thanks!
