### ISSUE TITLE
R.download recipe

### ISSUE THREAD

**Issue by cumcitjamfadmin** [autopkg/homebysix-recipes#510]
For https://github.com/autopkg/homebysix-recipes/blob/master/R/R.download.recipe, R now offers one .pkg for Intel and a different for ARM. Download URLs look like:

https://cran.r-project.org/bin/macosx/base/R-4.1.3.pkg
https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.1.3-arm64.pkg

I tried copying and editing the recipe to have a separate recipe for the ARM .pkg, but I don't understand Python regex enough to get it working. Would it be possible to create a separate recipe for the ARM .pkg?

**Comment by homebysix** [comment]
Hi @cumcitjamfadmin - I just adjusted the R recipes to accept a new `ARCH` input variable, which should let you specify which architecture you want. Note that you can create multiple overrides for the same R recipe, each with different architectures specified, if you want.

**Comment by mikaellofgren** [comment]
Hi!
It looks like they change the Download URL for Intel to use similar (**big-sur-x86_64**) as for ARM, that needs an update:

Intel: (new path):
https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.0-x86_64.pkg
Intel (Old):
https://cran.r-project.org/bin/macosx/base/R-4.1.3.pkg

Silicon/ARM (still working):
https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.3.0-arm64.pkg
