### ISSUE TITLE
SnapGeneViewer stops working

### ISSUE THREAD

**Issue by Peter-Erik** [autopkg/homebysix-recipes#514]
Hi I see an error running the snapgeneviewer.munki recipe.

The following recipes failed:
    snapgeneviewer.munki
        Error in local.munki.snapgeneviewer: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://www.snapgene.com/local/targets/viewer_download.php?os=mac&majorRelease=latest&minorRelease=latest', '--fail', '--output', '/Users/sysadm/Library/AutoPkg/Cache/local.munki.snapgeneviewer/downloads/tmplyibib9w']' returned non-zero exit status 22.

If I look at the download link in "SnapGeneViewer.download.recipe:   

https://www.snapgene.com/local/targets/viewer_download.php?os=mac&amp;majorRelease=%majorRelease%&amp;minorRelease=%minorRelease%

And if I look on the site there is an difference:

https://www.snapgene.com/local/targets/download.php?variant=viewer&os=mac&majorRelease=latest&minorRelease=latest

can this be fixed?  thanks

**Comment by homebysix** [comment]
Just merged https://github.com/autopkg/homebysix-recipes/pull/512 — try repo-update, then run again?

**Comment by Peter-Erik** [comment]
@homebysix  - Problem is fixed, thanks..

**Comment by Peter-Erik** [comment]
Close issue.
