### ISSUE TITLE
Inkscape munki recipe error

### ISSUE THREAD

**Issue by xastherion** [autopkg/homebysix-recipes#522]
Hello homebsix,

I think inkscape change again her path along the last update of this recipe.

**I am becoming this error over autopkgr:**

The following failures occurred:
RECIPE	MESSAGE
local.munki.Inkscape	Error in local.munki.Inkscape: Processor: URLTextSearcher: Error: No match found on URL: https://inkscape.org/release
The following errors occurred:
No match found on URL: https://inkscape.org/release Failed.

**and this if i run it on autopkg with -vvv   :**

 'SEARCH_PATTERN1': '(/release/inkscape-([0-9]{1,3}.[0-9]{0,3}.[0-9]{0,3})/mac-os-x/dmg/dl/)',
 'SEARCH_PATTERN2': '(?P<dmgurl>\\/gallery\\/.*Inkscape.*dmg)',
 'SEARCH_URL': 'https://inkscape.org',
 'VIRUSTOTAL_ALWAYS_REPORT': True,
 'pkginfo': {'catalogs': ['testing'],
             'description': 'Vector graphics application.',
             'developer': 'The Inkscape Project',
             'display_name': 'Inkscape',
             'name': 'Inkscape',
             'unattended_install': True},
 'verbose': 3}
URLTextSearcher
{'Input': {'re_pattern': '(/release/inkscape-([0-9]{1,3}.[0-9]{0,3}.[0-9]{0,3})/mac-os-x/dmg/dl/)',
           'result_output_var_name': 'release_page_match',
           'url': 'https://inkscape.org/release'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://inkscape.org/release
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://inkscape.org/release
Failed.
Receipt written to /Users/administrator/Library/AutoPkg/Cache/local.munki.Inkscape/receipts/Inkscape.munki-receipt-20220519-113604.plist

The following recipes failed:
    Inkscape.munki.recipe
        Error in local.munki.Inkscape: Processor: URLTextSearcher: Error: No match found on URL: https://inkscape.org/release

Nothing downloaded, packaged or imported.

**i Think it hang on the SEARCH_PATH variable, but maybe i am doing something wrong.**

Thanks a lot for your help in advance!

Xastherion

**Comment by homebysix** [comment]
Hello! This error is occurring in the URLTextSearcher process, which is part of the parent download recipe, which lives in another repo. I'd recommend opening an issue there: https://github.com/autopkg/hansen-m-recipes/blob/master/Inkscape/Inkscape.download.recipe
