### ISSUE TITLE
Zoom Version Issue for JAMF

### ISSUE THREAD

**Issue by MlooneyHV** [autopkg/homebysix-recipes#526]
Hello,

I love the Version Splitter! The current issue we are experiencing is that Zoom reports a weird version in JAMF.

The version pulled by Autopkgr for example is 5.11.0.8323

In JAMF however, the zoom version on machines shows as 5.11.0 (8323)

Is there any way to get the version splitter to add the parantheses onto the version number in Autopkgr (for smart group updating via Autopkgr) or remove those last 4 digits from the version? 

Ex. Policy runs with version splitter in the pkg.recipe, uploads updated package in JAMF and updates smart group to look for zoom version 5.11.0 (8323)
or
Ex. Policy runs with version splitter in the pkg.recipe, uploads updated package in JAMF and updates smart group to look for zoom version like 5.11.0

**Comment by MlooneyHV** [comment]
I'm confused. Does VERSIONTYPE? Work? How would I use it in the case with Zoom? Could you provide an example?

**Comment by MlooneyHV** [comment]
Still experiencing this issue and can't find a viable solution

**Comment by homebysix** [comment]
Hi @MlooneyHV - I just merged in https://github.com/autopkg/homebysix-recipes/pull/539, which may help with this. Could you give it a test?

**Comment by MlooneyHV** [comment]
Looks like the issue is now fixed.

**Comment by MlooneyHV** [comment]
Thank you!
