### ISSUE TITLE
Experiencing problems with multiple packages

### ISSUE THREAD

**Issue by delize** [autopkg/homebysix-recipes#53]
Failures occurred in these recipes:
com.github.homebysix.munki.licecap
com.github.homebysix.munki.KeePassX
com.github.homebysix.munki.ApacheDirectoryStudio
com.github.homebysix.pkg.Tunnelblick
com.github.homebysix.munki.Tunnelblick
com.github.homebysix.install.Tunnelblick
com.github.homebysix.download.Tunnelblick
com.github.homebysix.download.ParallelsDesktop
com.github.homebysix.install.ParallelsDesktop
com.github.homebysix.munki.ParallelsDesktop
com.github.homebysix.pkg.ParallelsDesktop
com.github.homebysix.pkg.BetterTouchTool
com.github.homebysix.munki.BetterTouchTool
com.github.homebysix.install.BetterTouchTool

This was attempted using AutoPKG, is there any known reason for these packages to fail?

**Comment by homebysix** [comment]
Hi @delize. All the recipes you mentioned work for me. It might be helpful for me to see the verbose output from one of your AutoPkg recipe runs. For example: `autopkg run -v com.github.homebysix.download.Tunnelblick`

**Comment by delize** [comment]
The output from that command is:

 

> autopkg run -v com.github.homebysix.download.Tunnelblick
> Processing com.github.homebysix.download.Tunnelblick...
> Failed.
> Receipt written to /tmp/receipts/com.github.homebysix.download-receipt-20160330-145042.plist
> 
> The following recipes failed:
>     com.github.homebysix.download.Tunnelblick
>         Recipe (or a parent recipe) requires at least version 0.6.1, but we are version 0.5.2.
> 
> Nothing downloaded, packaged or imported.

**Comment by delize** [comment]
Okay, I see where the problem is, I am guessing it is referring to AutoPKG itself. I went ahead and updated to v6.1 and after running the command again, it proceeds to download, package and import Tunnelblick.

Thanks, sorry about the useless ticket.

**Comment by homebysix** [comment]
Glad to hear you solved it! :-)

**Comment by homebysix** [comment]
Yep, that's the way it's supposed to run.

I've seen the "not mounted" error before when I manually mount the same DMG prior to running the recipe, but it doesn't happen for me normally.
