### ISSUE TITLE
MountainDuck.download producing double-escaped URL

### ISSUE THREAD

**Issue by AllPurposeBen** [autopkg/homebysix-recipes#531]
In what I think is a similar issue to https://github.com/autopkg/homebysix-recipes/pull/347, in MountainDuck.download, the output from `SparkleUpdateInfoProvider` is getting a double escaped space:
```
SparkleUpdateInfoProvider: Found URL https://dist.mountainduck.io/Mountain%2520Duck-4.12.1.19928.zip
```
The output from the [raw sparkle RSS](https://version.mountainduck.io/changelog.rss) looks right and matches the URL from download button on their site:
```
sparkle:edSignature="VaO9yj8OsvqTIdwnCyDiJXgGIOF2CHIZfkroMAVJddjWjKokD/QpbKx/YxDFE41u9pp3Yj/WtsG+GSh1eEEDCg==" url="https://dist.mountainduck.io/Mountain%20Duck-4.12.1.19928.zip" type="application/octet-stream"/>
```
...but `SparkleUpdateInfoProvider` seems to be mangling it. 

Not sure if the[ same fix](https://github.com/autopkg/homebysix-recipes/pull/347/commits) should apply or if this or if it might be something goofy in `SparkleUpdateInfoProvider` worth raising in the autopkg repo?

**Comment by homebysix** [comment]
I don't see a MountainDuck.download recipe in this repository. I do see one in ahousseini-recipes and rtrouton-recipes. Could that be the recipe you mean?

**Comment by AllPurposeBen** [comment]
Yes, crap, sorry, I was looking at the rtrouton one and had both repos open to reference your related fix and started the issue in the wrong tab. My bad!

**Comment by AllPurposeBen** [comment]
Yes, crap, sorry, I was looking at the rtrouton one and had both repos open to reference your related fix and started the issue in the wrong tab. My bad!
