### ISSUE TITLE
PureRef recipe does not get latest version

### ISSUE THREAD

**Issue by gregneagle** [autopkg/homebysix-recipes#536]
Thanks for writing these recipes!

Running PureRef.munki today downloaded and imported version 1.10.4.
Current version is 1.11.1, which can be manually downloaded from https://www.pureref.com/download.php :-(

**Comment by gregneagle** [comment]
Looks like the issue is here:
```xml
<span id="versionSelect" class="custom-dropdown">
				<select>
					<option selected value="1.11.1">1.11.1</option><option value="1.10.4">1.10.4</option>				</select>
			</span>
```
The URLTextSearcher is looking for the version using "option value=", which is (currently) pointing to an older version.

**Comment by homebysix** [comment]
Thanks! Fixed in https://github.com/autopkg/homebysix-recipes/pull/551.
