### ISSUE TITLE
Grammarly Recipes Don't Pull Latest Version

### ISSUE THREAD

**Issue by rougegoat** [autopkg/homebysix-recipes#542]
I've noticed on the last few updates that Grammarly will often take days or weeks to get the newest version pulled in.  For example, version 1.13.0 was released on 10/13/2022, but these recipes are still pulling 1.12.1 as of 10/18/2022.  I'm guessing the download URL may need to be updated.

**Comment by homebysix** [comment]
As of now, I'm getting version 1.28.4 from both AutoPkg and the Grammarly direct download. Feel free to re-open if this happens again.

**Comment by rougegoat** [comment]
This usually happens after a major update (i.e. 1.13 > 1.14) but not after minor updates (i.e. 1.28.0 > 1.28.4)
