### ISSUE TITLE
Eclipse code signatures now unique per-IDE

### ISSUE THREAD

**Issue by mpanighetti** [autopkg/homebysix-recipes#554]
[The shared code signature in Eclipse.download.recipe](https://github.com/autopkg/homebysix-recipes/blob/d8ee677aa181c24ddefff6d4f762d71dffae2a2c/Eclipse/Eclipse.download.recipe#L100) is no longer used in Eclipse app downloads, and the apps now appear to each have unique code signature identifiers. Two example code signature outputs below.

Eclipse IDE for Java Developers:
```
$ codesign -dr - /Volumes/Eclipse/Eclipse.app 
Executable=/Volumes/Eclipse/Eclipse.app/Contents/MacOS/eclipse
designated => identifier "epp.package.java" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = JCDTMS22B4
```

Eclipse IDE for C/C++ Developers:
```
$ codesign -dr - /Volumes/Eclipse/Eclipse.app 
Executable=/Volumes/Eclipse/Eclipse.app/Contents/MacOS/eclipse
designated => identifier "epp.package.cpp" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = JCDTMS22B4
```

Theoretically this could be addressed by including the identifier as a new input variable and providing instructions when creating recipe overrides. Other solution would be to split the download recipe to target each IDE build and unique identifier.

**Comment by nstrauss** [comment]
I believe my PR covers this change. https://github.com/autopkg/homebysix-recipes/pull/563

**Comment by mpanighetti** [comment]
#563 has been merged, confirmed my recipe overrides are working again. Thanks for the fix!
