### ISSUE TITLE
Royal TSX Fails to download

### ISSUE THREAD

**Issue by seansgm** [autopkg/homebysix-recipes#56]
`Processor: URLTextSearcher: Error: No match found on URL: http://www.royalapplications.com/ts/osx/download`

**Comment by seansgm** [comment]
Created a pull request: https://github.com/autopkg/homebysix-recipes/pull/57/commits/225c5ed3d43a3c50d1810e10c5e0ba1beb209fbb

**Comment by homebysix** [comment]
Thanks!
