### ISSUE TITLE
Spotify package only getting Apple Silicon

### ISSUE THREAD

**Issue by joshnovotny** [autopkg/homebysix-recipes#567]
As of 1.2.3.1115, the recipe is pulling the Apple Silicon version so it does not work on Intel Macs. Looking at 1.2.0.1165, it is pulling in the Intel version.

**Comment by mpanighetti** [comment]
Spotify platform architecture is defined by input variables in the parent [Spotify.download.recipe](https://github.com/autopkg/recipes/blob/master/Spotify/Spotify.download.recipe#L8-L10).
