### ISSUE TITLE
Docker Desktop on M1 macs?

### ISSUE THREAD

**Issue by JoblessLoser** [autopkg/homebysix-recipes#572]
Hi ,Thanks for making this code available.

Given that Docker is only functioning on intel macs would it make sense to include the
Supported architectures x86_64 flag?

(I speak in ignorance as I do not make use of Docker)

Many thanks

**Comment by mpanighetti** [comment]
[Docker has supported Apple Silicon for awhile now](https://www.docker.com/blog/released-docker-desktop-for-mac-apple-silicon/), as long as you have a compatible image. [The download recipe has its `%PLATFORM_ARCH%` input variable set to `amd64` by default](https://github.com/autopkg/homebysix-recipes/blob/master/Docker/DockerDesktop.download.recipe#L11), which is the value used for the Intel build's download URL.
