### ISSUE TITLE
PureRef.munki - Munkiimport Error

### ISSUE THREAD

**Issue by jannheider** [autopkg/homebysix-recipes#573]
Getting Following Error when running with Autopkg:

```
The following recipes failed:
    PureRef.munki
        Error in local.munki.PureRef: Processor: MunkiImporter: Error: no element found: line 188365, column 20
```

At the moment I cloud not debug the problem

**Comment by homebysix** [comment]
Please clear the cache and then try `autopkg run -vv PureRef.munki MakeCatalogs.munki` and share the output here. Thanks!

**Comment by jannheider** [comment]
Thanks for the fast reply, actually it was a broken munki make catalog run caused by poor network latency caused by Problemen in the datacenter.

Everything is fine with you recipe.

Thanks!

**Comment by jannheider** [comment]
We can close this issue.
