### ISSUE TITLE
Parallels recipe not downloading the latest Parallels Desktop 18 Version

### ISSUE THREAD

**Issue by macmangr** [autopkg/homebysix-recipes#576]
Hi,
I am using the recipe for Parallels Desktop 18 and recently noticed that it is not downloading the latest version. After some experimenting and testing I have the following PR suggestion. It works for versions 10 through 18:

```
...
	<key>Description</key>
	<string>Downloads the major version of Parallels Desktop specified by MAJOR_VERSION. This recipe has been tested with major versions 10 through 18.

For major versions 10 through 15 and 18, leave the PLATFORM_ARCH blank in your override.

For major version 16, set the PLATFORM_ARCH in your override to either "/intel" or "/m1" depending on your desired architecture.

For major version 17, set the PLATFORM_ARCH in your override to "/image"

This recipe differs from the one in keeleysam-recipes because it offers code signature verification, does not require a ParallelsURLProvider processor, and also includes pkg and install recipes.</string>
	<key>Identifier</key>
...
<key>Process</key>
	<array>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>re_pattern</key>
				<string>(https.*?%MAJOR_VERSION%(.*?)(?=\?|\"))</string>
				<key>result_output_var_name</key>
				<string>url_version</string>
				<key>url</key>
				<string>https://download.parallels.com/website_links/desktop/%MAJOR_VERSION%/builds-en_US.json</string>
			</dict>
			<key>Processor</key>
			<string>URLTextSearcher</string>
		</dict>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>filename</key>
				<string>%NAME%.dmg</string>
				<key>url</key>
				<string>%url_version%%PLATFORM_ARCH%</string>
			</dict>
			<key>Processor</key>
			<string>URLDownloader</string>
		</dict>
...
```

**Comment by patthew** [comment]
Very nice! Any way to inject a license key?

**Comment by macmangr** [comment]
In this case the management tools are needed to create an autodeploy package where the license key can be entered in the deploy.cfg file. Parallels has a good guide on how to do this...

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi3xsH6lOH-AhWTSvEDHekUAmEQFnoECAsQAQ&url=https%3A%2F%2Fdownload.parallels.com%2Fdesktop%2Fv18%2Fdocs%2Fen_US%2FParallels-Desktop-Business-Edition-Administrators-Guide.pdf&usg=AOvVaw2XBlhXVfSmDTrI_42jTcgy

**Comment by homebysix** [comment]
Thanks!

**Comment by patthew** [comment]
> 

Ah yeah so my original issue is that Intune does not like the unsigned, non-flat Parallels autodeploy pkg, which led me here. I actually got the licensing working with this, but Intune still doesn't like the pkg format for whatever reason. Thanks MS :)
