### ISSUE TITLE
ViennaRSS stuck on v3.8.2 when latest is v3.8.6

### ISSUE THREAD

**Issue by fseesink** [autopkg/homebysix-recipes#577]
Visiting the GitHub repo, realized **ViennaRSS** has had 4 updates since Aug 2022 that never showed up.

Running `autopkg run -vv Vienna.munki.recipe`, I notice that it's finding 3.8.2 instead of 3.8.6.  Not sure what has changed or why it's finding this version and not the latest. I do see that the download recipe hasn't changed since Oct 2021.

Anyway, figured I'd mention this.

**Comment by homebysix** [comment]
Should be fixed in #578. Thanks!
