### ISSUE TITLE
GraphicConverter.download is pulling a beta version

### ISSUE THREAD

**Issue by grahampugh** [autopkg/homebysix-recipes#598]
Hi Elliot, we've noticed that the GC recipe is currently pulling down 12.0.4 beta version. This happens to be the latest version in the Sparkle feed. Unfortunately the sparkle channel is only set for beta, not for production, so you can't specify a channel to get the right version. We also can't see any other keys that would help.

I'm wondering if it would be better to scrape and pull the DMG directly from the webpage (https://www.lemkesoft.de/en/products/graphicconverter/download/)?

**Comment by homebysix** [comment]
Hi @grahampugh - I'm not able to reproduce this. Could you provide the `-vv` output from SparkleUpdateInfoProvider? Mine looks like this:

```
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://www.lemkesoft.info/sparkle/graphicconverter/graphicconverter12.xml'}}
SparkleUpdateInfoProvider: Items in feed: 5
SparkleUpdateInfoProvider: Items in default channel: 4
SparkleUpdateInfoProvider: Version retrieved from appcast: 6157
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 12.0.2
SparkleUpdateInfoProvider: Found URL https://www.lemkesoft.info/files/graphicconverter/gc12_build6157.zip
{'Output': {'url': 'https://www.lemkesoft.info/files/graphicconverter/gc12_build6157.zip',
            'version': '12.0.2'}}
```

**Comment by grahampugh** [comment]
Hi Elliot, sure, here is the output when running `autopkg run -vv GraphicConverter.download --key MAJOR_VERSION=12`:

```
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://www.lemkesoft.info/sparkle/graphicconverter/graphicconverter12.xml'}}
SparkleUpdateInfoProvider: Version retrieved from appcast: build6176
SparkleUpdateInfoProvider: Found URL https://www.lemkesoft.org/beta/gc12_build6176.zip
{'Output': {'url': 'https://www.lemkesoft.org/beta/gc12_build6176.zip',
            'version': 'build6176'}}
```

This results in:

```
Versioner: Found version 12.0.4 in file /Users/gpugh/Library/AutoPkg/Cache/com.github.homebysix.download.GraphicConverter/GraphicConverter/Applications/GraphicConverter 12.app/Contents/Info.plist
{'Output': {'version': '12.0.4'}}
```

**Comment by homebysix** [comment]
Are you running a custom branch of AutoPkg, or an older version? I'm on 2.7.2, and channel support was added to SparkleUpdateInfoProvider recently.

**Comment by homebysix** [comment]
I'm on the fence about whether that's a problem I need to solve. On one hand, it's ultimately the developer's responsibility to update the Sparkle feed, and using Sparkle as the source for AutoPkg offers easy major-version overrides and supports default/beta channels.

On the other hand, it looks like multiple major versions and beta versions can probably be derived from the static URLs available on the download page too, so it wouldn't be difficult to implement your suggestion.
