### ISSUE TITLE
Docker Supported architecture 

### ISSUE THREAD

**Issue by JoblessLoser** [autopkg/homebysix-recipes#631]
The docker munki recipe currently only downloads the Docker-amd64-version.dmg which only works on x86_64 architecture. 

The Docker-arm64-version.dmg file which only works on arm_64 architecture is not catered for.

**Comment by homebysix** [comment]
Is the `PLATFORM_ARCH` input variable not working for you?

**Comment by gregneagle** [comment]
https://github.com/autopkg/homebysix-recipes/blob/master/Docker/DockerDesktop.download.recipe#L10-L24
You'd make _two_ overrides: one for Intel, and one for Apple silicon. You'd set the appropriate value in `PLATFORM_ARCH` in the override.

https://github.com/autopkg/homebysix-recipes/blob/master/Docker/DockerDesktop.munki.recipe#L17-L33
In your overrides, you'd also want to override the pkginfo to include the appropriate supported_architectures.

**Comment by JoblessLoser** [comment]
Thanks, as I was missing this step I'm guessing this will solve my problem.
