### ISSUE TITLE
iMazing recipes and new version 3

### ISSUE THREAD

**Issue by jelockwood** [autopkg/homebysix-recipes#634]
The existing iMazing recipe written by @homebysix is using the Sparkle method to find updates and AutoPkg supports this and can scan the Sparkle appcast XML feed to find updates.

However the current recipe is coded to look for https://downloads.imazing.com/com.DigiDNA.iMazing2Mac.xml which only lists version 2 updates.

Recently version 3 of iMazing has been released and this is a free upgrade if you are paying the annual subscription for iMazing but it is not found via the version 2 appcast feed.

I don't think the right solution would be to modify the existing recipe to look at the version 3 appcast URL, I think it would be more appropriate to create a new recipe looking at the version 3 appcast URL.

It should be noted that while the now standard business _subscription_ license allows upgrading to version 3, the now no longer available Enterprise license does not. As it was the same program merely with a different license, upgrading a user with an Enterprise license to version 3 would 'break' their license.

I also found a second different set of recipes for iMazing written by @apizz which whilst it has the same issue of only supporting version 2 uses a different approach to find and download updates. It scrapes the iMazing website for https://downloads.imazing.com/mac/iMazing/iMazing2forMac.dmg and is therefore hardcoded for version 2 updates. The new URL is https://downloads.imazing.com/mac/iMazing/iMazing3forMac.dmg

It would I believe be possible to use a recipe override to override either the appcast_url or url keys respectively, however as mentioned I feel it is a better idea to have a separate recipe for version 3.

I have therefore created a download and munki recipe for version 3 and they are available at the following URL. The download recipe uses the same Sparkle method as the original one written by @homebysix but updated to scan the version 3 appcast URL.

https://github.com/jelockwood/recipes/tree/master/iMazing3

**Comment by homebysix** [comment]
The intent of my recipe isn't to only provide version 2, but rather to provide the "latest." It's up to the users of my recipe whether they want to _distribute_ the latest.

So I'm going to add a `MAJOR_VERSION` input variable set to 3 by default, but people can choose to set it to 2 in their override if they prefer.

**Comment by jelockwood** [comment]
Sounds a good solution. It is now likely to not be as relevant as when I first opened this issue as iMazing have stopped supporting version 2 so it is unlikely any further updates will be issued. 

When I originally raised this version 2 still worked on the then latest macOS but it now does not work on Sequoia. As a result I will be at my company seeking a budget to replace the old non-expiring Enterprise (v2  only) licenses with the subscription licenses which allow using v3.
