### ISSUE TITLE
Bartender 5 - change of signing 

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/homebysix-recipes#639]
The Bartender recipe is currently broken for v5 as the signing certificate changed in the latest release. The new signing info is:

`anchor apple generic and identifier "com.surteesstudios.Bartender" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "24J875RH8J")`

**Comment by flammable** [comment]
https://github.com/autopkg/homebysix-recipes/pull/637 will solve this.

**Comment by homebysix** [comment]
Thanks, merged.
