### ISSUE TITLE
In AutoPkgr, BitTorrent Sync munki recipe kicking up "Code signature verification failed" message.

### ISSUE THREAD

**Issue by fseesink** [autopkg/homebysix-recipes#65]
Just in the past few days, started getting this dialog box while running my recipes:
![screen shot 2016-06-24 at 1 26 40 pm](https://cloud.githubusercontent.com/assets/48991/16345531/7486fe42-3a10-11e6-9e04-cb2ea1a78eb8.png)

I eventually tracked it down to the BitTorrentSync.munki.recipe.  I have it overridden, but just for some minor tweaks.  Doing some searching, found this:
https://github.com/autopkg/homebysix-recipes/issues/32

and followed similar steps in my override to suppress the error.

But wanted to let you know just the same, as I suspect others will see this, too.

**Comment by homebysix** [comment]
Thanks @fseesink, I noticed this too and have been meaning to take a look.

It appears as if BitTorrent Sync has updated their code signing, so I've updated my download recipe to match (https://github.com/autopkg/homebysix-recipes/commit/0d7003a3b5b378281331f82d82e8df338accc399). Please update the repo and try again, and let me know whether that solves the error for you.

**Comment by fseesink** [comment]
@homebysix Yep, seems to be working fine now.  I removed the mod to my override and tested, and got error again.  Then updated the repo and tested one more time, and all worked as expected.  So looks good.
