### ISSUE TITLE
Resilio 3.0 download link appears to have changed / ResilioSync.download.recipe not pulling latest version

### ISSUE THREAD

**Issue by fseesink** [autopkg/homebysix-recipes#654]
The current `ResilioSync.download.recipe` is using URL
```
https://download-cdn.resilio.com/stable/osx/Resilio-Sync.dmg
```

But it looks like the current v3.0 release (not sure when that dropped) now shows this link on the downloads page:
```
https://download-cdn.resilio.com/stable/mac/osx/0/Resilio-Sync.dmg
```

**Comment by homebysix** [comment]
Thanks! I updated the download URL in #655.
