### ISSUE TITLE
DuetDisplay - Change in Downloaded File Format

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/homebysix-recipes#661]
Hi, @homebysix 

Duet have changed the downloaded file format from .zip to .dmg on the latest version DuetDesktop for [macOS 11+](https://updates.duetdisplay.com/AppleSilicon)

Unfortunately the legacy application for [10.13 - 10.15](https://updates.duetdisplay.com/IntelMac) hasn't yet (and possibly may never be?) been updated to the new format and is still a .zip file.

I've got a [PR ready to be raised](https://github.com/paul-cossey/homebysix-recipes/commit/10215059720b5ac3eef6132d0927fe0660898a44) that'll update the download and munki recipes to use the new format, but this will break support for the legacy downloads. 

Not sure if you want to drop support and have separate recipes the legacy version? Or just drop support entirely?

**Comment by homebysix** [comment]
I'm open to dropping the legacy support and switch the recipe to download the latest version.

**Comment by paul-cossey** [comment]
Done! https://github.com/autopkg/homebysix-recipes/pull/662
