### ISSUE TITLE
UnRarX download broken

### ISSUE THREAD

**Issue by aysiu** [autopkg/homebysix-recipes#68]
I don't think it can be fixed right now.

Apparently, http://www.unrarx.com is completely down (the host has suspended the account), so the http://www.unrarx.com/update.xml link definitely doesn't work.

Apart from that official site, all there is left is SoftTonic, MacUpdate, CNET, etc.

Even SourceForge's page just points you to the dead link.

**Comment by homebysix** [comment]
I've been watching this for a week or so, and I think it's a temporary outage. I'm going to leave the recipes as is for now.

**Comment by aysiu** [comment]
Cool. Maybe they had a bandwidth limit or didn't pay their hosting bill.

**Comment by homebysix** [comment]
As expected, the website is back up. The UnRarX recipes should work again now. Thanks!

**Comment by aysiu** [comment]
Awesome!
