### ISSUE TITLE
YemuZip download recipe looking for old version

### ISSUE THREAD

**Issue by aysiu** [autopkg/homebysix-recipes#69]
The download recipe is looking at http://www.yellowmug.com/yemuzip/appcast.xml for the latest version.

That .xml file is reporting the latest as 2.4.3 from January 17, 2012.

If you go to the main download page, though, the latest version is actually 2.5, and it appears to allow code signature verification. I'm going to see if I can throw together a pull request...

**Comment by aysiu** [comment]
Fixed in this pull request:
https://github.com/autopkg/homebysix-recipes/pull/70

**Comment by homebysix** [comment]
Thanks!
