### ISSUE TITLE
UnRarX download recipe still getting beta

### ISSUE THREAD

**Issue by aysiu** [autopkg/homebysix-recipes#79]
The newer version is 2.2, but the UnRarX download recipe keeps pulling 2.2 beta from
http://www.unrarx.com/update.xml

**Comment by aysiu** [comment]
Actually, this may be a non-issue. The 2.2 binary is the exact same (via checksum) binary as the 2.2b one. The only problem, of course, is that when you launch up UnRarX 2.2b, it checks for an update and then sees a "newer" version is out (2.2) and prompts you to update.

**Comment by homebysix** [comment]
If this is an issue, I suspect it's something that would need to be clarified in SparkleUpdateInfoProvider.

Alternatively, we could switch to URLTextSearcher, since there's a download link available on www.unrarx.com. Is it worth it?

**Comment by aysiu** [comment]
I'm inclined to go with URLTextSearcher. If you don't have the mental bandwidth for it, I can make a pull request. Let me know what you prefer.

**Comment by homebysix** [comment]
Thanks! I'll tweak this a little.
