### ISSUE TITLE
BitTorrent Sync is now Resilio Sync

### ISSUE THREAD

**Issue by flammable** [autopkg/homebysix-recipes#83]
Hey Elliot!

I noticed that BitTorrent Sync has changed their name - with version 2.4.0, it's now known as Resilio Sync:

https://www.getsync.com/individuals/

What's the best way to handle this?  Should the old recipe be retired of a new one, or the existing recipe be renamed?

Also, I'm thinking I'll add BitTorrent Sync to blocking_applications and include this as a postinstall_script:

```
#!/bin/bash

rm="/bin/rm"

${rm} "/Applications/BitTorrent Sync.app"

exit 0
```

(via an override, of course)

Mike

**Comment by homebysix** [comment]
Given the name change, I think it's better to create a brand new recipe with the Resilio name.

To make the transition smooth, I could make the existing recipes into "aliases" that simply point to the new recipes via ParentRecipe, with the understanding that the old ones would be deprecated.

I agree with your blocking_applications and postinstall_script ideas. Do you want to host the new Resilio recipes, or should I whip some up?

**Comment by flammable** [comment]
Would you be cool with doing it?  I think I've almost fleshed this out, but I'm still a little foggy on some of the details.

Thanks!

Mike

**Comment by homebysix** [comment]
Done! Care to give it a try?

I also gave the pkg a postinstall.

**Comment by flammable** [comment]
Looks fantastic, thanks!  I like your postinstall script better than mine. 👍 

One question: should Resilio Sync itself be listed in blocking_applications?  I couldn't tell from the wiki page if listing items in blocking_applications merges with the installs array, or if it overrides them.

https://github.com/munki/munki/wiki/Blocking-Applications

**Comment by gregneagle** [comment]
Yes, you need to add it. blocking_applications is the definitive array; it's not combined with info from the installs array.

The installs array is used only if blocking_applications does not exist.
