### ISSUE TITLE
i have an error

### ISSUE THREAD

**Issue by aa-it-autopkg** [autopkg/homebysix-recipes#95]
No match found on URL: http://continuum.io/downloads

Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

Error processing path '/private/tmp/dmg.PrUtbK/Tableau Reader.app' with glob.

**Comment by homebysix** [comment]
Hi @aa-it-autopkg,

Could you try again after pulling the latest changes from the repo? I made some updates to the Tableau Reader recipes.
