### ISSUE TITLE
Getting an error on Zoom Recipe

### ISSUE THREAD

**Issue by benmartel** [autopkg/homebysix-recipes#98]
The error I am getting when running the recipe is: 

`Unarchiving ~/Library/Autopkg/Cache/local.jss.zoom/expanded/Scripts/zm.zip with ditto failed : ditto: ~/Library/Autopkg/Cache/local.jss.zoom/expanded/Scripts/zm.zip no such file or directory. `

That has been cleaned up to be a little more generic of a path but I think the idea still comes across

I believe the error lies in this part of the code: https://github.com/autopkg/homebysix-recipes/blob/master/Zoom/Zoom.pkg.recipe#L53-L59

When I look at that folder I see `zm.7z` and `7zr.zip`

**Comment by homebysix** [comment]
Will be fixed by https://github.com/autopkg/homebysix-recipes/pull/97, which I haven't had a chance yet to test.

**Comment by benmartel** [comment]
Thank you for your quick work on this.

**Comment by kitzy** [comment]
@homebysix I just tested the changes and they're working for me, FWIW.

**Comment by homebysix** [comment]
OK, I'll merge in now based on @kitzy's recommendation, and tweak later if needed. Thanks!

**Comment by rdamienc** [comment]
I am seeing a similar error:

`The following recipes failed:
    Zoom.munki
        Error in com.github.homebysix.munki.Zoom: Processor: Unarchiver: Error: Unarchiving /Users/user/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/expanded/Scripts/7zr.zip with ditto failed: ditto: /Users/user/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/expanded/Scripts/7zr.zip: No such file or directory`

The /Users/user/Library/AutoPkg/Cache/com.github.homebysix.munki.Zoom/expanded/Scripts directory is empty.

**Comment by raufis27** [comment]
Same issue AutoPkg/Cache/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip: No such file or directory

**Comment by mikaellofgren** [comment]
Yes same here:
7zr.zip with ditto failed: ditto: 
/Library/AutoPkg/Cache/local.munki.Zoom/expanded/Scripts/7zr.zip: No such file or directory
